# aggregator configuration
listenAddr: "0.0.0.0:7777"                                  # address proxy listens on, set miners to this devices IP and this port.
scanTime: 200                                               # your maximum scantime in seconds (collision avoidance only need adjustment if multi-mining)
displayMiners: true                                         # displays info on connected miners at the beginning of each round

#primary chain
primarySubmitURL: "https://signapool.notallmine.net"	    # primary chain:    url of nam pool
primaryTargetDeadline: 31536000                             # primary chain:    target deadline
primaryPassphrase: ""                                       # primary chain:    passphrase overwrite (not used for nam)
primaryIpForwarding: false                                  # primary chain:    set X-Forwarded-For Headder                                
primaryIgnoreWorseDeadlines: true                           # primary chain:    ignore a deadline if a better deadline has already been found. 
primaryAccountKey: ""                                       # primary chain:    account key (not used for nam) 

# additonal info
minerName: "Aggregator"                                     # miner name
minerAlias: ""                                              # miner alias

# logging
fileLogging: false                                          # log information to log.txt

# aggregator protection
minersPerIP: 100                                            # miners allowed per ip
rateLimit: 45                                               # maximum requests per second per IP
burstRate: 10                                               # rate limiter burst rate
lieDetector: false                                          # ignore miner for 15min if false deadline has been sent
