# aggregator configuration
listenAddr: "0.0.0.0:7777"                                  # address proxy listens on, set miners to this devices IP and this port.
scanTime: 200                                               # your maximum scantime in seconds (collision avoidance only need adjustment if multi-mining)
displayMiners: true                                         # displays info on connected miners at the beginning of each round

#primary chain
primarySubmitURL: "https://signapool.notallmine.net"        # primary chain:    url to forward nonces to (pool, wallet)
primaryTargetDeadline: 31536000                             # primary chain:    target deadline
primaryPassphrase: ""                                       # primary chain:    passphrase overwrite (optional), empty -> passphrase from client will be forwarded if any
primaryIpForwarding: false                                  # primary chain:    set X-Forwarded-For Headder                                
primaryIgnoreWorseDeadlines: true                           # primary chain:    ignore a deadline if a better deadline has already been found (saves bandwidth). 
primaryAccountKey: ""                                       # primary chain:    account key (not needed for most pools)

#secondary chain
secondarySubmitURL: "wss://some.bhdpool.com"                # secondary chain:  url to forward nonces to (pool, wallet)
secondaryTargetDeadline: 1000000000                         # secondary chain:  target deadline
secondaryPassphrase: ""                                     # secondary chain:  passphrase overwrite (optional), empty -> passphrase from client will be forwarded if any
secondaryIpForwarding: false                                # secondary chain:  set X-Forwarded-For Headder                                
secondaryIgnoreWorseDeadlines: true                         # secondary chain:  ignore a deadline if a better deadline has already been found. 
secondaryAccountKey: ""                                     # secondary chain:  account key 

# additonal info
minerName: "Aggregator"                                     # miner name
minerAlias: ""                                              # miner alias

# logging
fileLogging: false                                          # log information to log.txt

# aggregator protection
minersPerIP: 100                                            # miners allowed per ip
rateLimit: 45                                               # maximum requests per second per IP
burstRate: 10                                               # rate limiter burst rate
lieDetector: false                                          # ignore miner for 15min if false deadline has been sent
