name: Release
on:
  push:
    tags:
      - "v*" # triggers only if push new tag version, like `0.8.4`
        
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: windows-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64,
        goos: [linux]
        goarch: ["386", amd64]

    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "Signum-Aggregator"
